# Generated by Django 5.1.1 on 2025-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='sub_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
