# Generated by Django 5.1.1 on 2025-01-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_remove_album_discogs_master_id'),
        ('stats', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='associated_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.artist'),
        ),
    ]
