# Generated by Django 5.1.1 on 2025-01-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_remove_album_discogs_master_id'),
        ('stats', '0005_badge_associated_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAlbumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.album')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('album', 'date')},
            },
        ),
    ]
