# Generated by Django 5.1.1 on 2025-01-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_dailyexchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyExchangeRate',
        ),
    ]
