# Generated by Django 5.1.1 on 2025-01-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_albumpriceprediction'),
        ('stats', '0009_albumpricepredictions'),
    ]

    operations = [
    ]
