# Generated by Django 5.1.1 on 2025-01-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_merge_20250115_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumPricePredictions',
        ),
    ]
