# Generated by Django 5.1.1 on 2025-01-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usd_to_eur', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
