# Generated by Django 5.1.1 on 2025-01-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('guest', 'Guest')], default='pending', max_length=10),
        ),
    ]
