# Generated by Django 5.1.1 on 2025-01-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friendlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='email',
            new_name='friend_email',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='name',
            new_name='friend_name',
        ),
    ]
