# Generated by Django 5.1.1 on 2024-12-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_useralbumdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
