# Generated by Django 5.1.1 on 2024-12-28 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_remove_album_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useralbumdescription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useralbumdescription',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
