# Generated by Django 5.1.1 on 2024-12-31 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_userartistprogress_blacklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_artists', models.IntegerField(default=0)),
                ('total_albums', models.IntegerField(default=0)),
                ('total_collection_count', models.IntegerField(default=0)),
                ('total_wishlist_count', models.IntegerField(default=0)),
                ('total_blacklist_count', models.IntegerField(default=0)),
                ('total_collection_and_wishlist_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
