# Generated by Django 5.1.1 on 2024-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralbumwishlist',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unspecified', 'Unspecified')], default='unspecified', max_length=15),
        ),
    ]
