# Generated by Django 5.1.1 on 2024-12-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_useralbumwishlist_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbumdescription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
