# Generated by Django 5.1.1 on 2024-12-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_alter_useralbumdescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralbumcollection',
            name='substatus',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('preordered', 'Preordered'), ('ordered', 'Ordered'), ('unspecified', 'Unspecified')], default='unspecified', max_length=25),
        ),
    ]
