# Generated by Django 5.1.1 on 2025-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_genre_remove_artist_genres_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='aliases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='discogs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
