# Generated by Django 5.1.1 on 2025-01-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_artist_aliases_artist_discogs_id_artist_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='highest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artist',
            name='urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
