# Generated by Django 5.1.1 on 2025-01-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_album_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='versions',
        ),
    ]
