# Generated by Django 5.1.1 on 2025-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_remove_album_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='album',
            name='highest_price',
        ),
        migrations.AlterField(
            model_name='artist',
            name='aliases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
