# Generated by Django 5.1.1 on 2025-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_remove_album_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
    ]
