# Generated by Django 5.1.1 on 2025-01-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_alter_artist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='formats',
        ),
    ]
