# Generated by Django 5.1.1 on 2025-01-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_remove_album_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='styles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
