# Generated by Django 5.1.1 on 2025-01-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_alter_album_genres_alter_album_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='discogs_master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
