# Generated by Django 5.1.1 on 2025-01-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_album_discogs_master_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='discogs_master_id',
        ),
    ]
