# Generated by Django 5.1.1 on 2025-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trigger_notification_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
